const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.route('**/api/**', async route => {
    const url = new URL(route.request().url());
    url.hostname = '127.0.0.1'; url.port = '5001';
    const response = await route.fetch({ url: url.toString() });
    await route.fulfill({ response });
  });
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:3001/login');
  await page.getByLabel('Email address').fill('qa@absoluturf.example');
  await page.getByLabel('Password', { exact: true }).fill('qa-password-123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.waitForURL('**/dashboard');
  await page.goto('http://localhost:3001/payments');
  const filter = page.getByRole('combobox', { name: 'Filter payment status' });
  await filter.click(); await page.getByRole('option', { name: 'To pay', exact: true }).click();
  await filter.focus(); await page.keyboard.press('ArrowDown');
  await page.getByRole('listbox').waitFor();
  await page.waitForTimeout(100);
  await page.keyboard.press('End');
  await page.waitForTimeout(100);
  await page.keyboard.press('Enter');
  await page.waitForTimeout(100);
  assert.match(await filter.innerText(), /Verified/);
  await filter.click(); await page.getByRole('listbox').waitFor(); await page.waitForTimeout(200);
  await page.screenshot({ path: __dirname + '/dropdown-desktop.png', fullPage: true });
  await page.keyboard.press('Escape');
  await page.goto('http://localhost:3001/groups?create=true');
  await page.getByRole('combobox').first().click();
  await page.getByRole('listbox').waitFor(); await page.waitForTimeout(200);
  await page.getByRole('option', { name: 'Cricket', exact: true }).click();
  assert.match(await page.getByRole('combobox').first().innerText(), /Cricket/);
  await page.goto('http://localhost:3001/matches?create=true');
  await page.getByRole('combobox', { name: 'Select group' }).click();
  await page.getByRole('option', { name: 'Weekend Football Club' }).click();
  await page.getByRole('button', { name: 'Select date', exact: true }).click();
  await page.locator('.picker-panel button').first().click();
  await page.getByRole('button', { name: 'Select time slot', exact: true }).click();
  await page.getByRole('heading', { name: 'Select Start Time' }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('http://localhost:3001/groups?create=true');
  await page.getByRole('combobox').first().click();
  await page.screenshot({ path: __dirname + '/dropdown-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('Passed: dropdown selection, keyboard navigation, group/date/time labels, mobile overflow and runtime checks.');
})().catch(e => { console.error(e); process.exit(1); });
